### ISSUE TITLE
message generation is picking up and documenting messages that are supposed to be hidden

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosdoc2#82]
Packages like rclcpp have test content in sub folders which are not advertised messages. However they're being added to the package documentation. 

![image](https://github.com/ros-infrastructure/rosdoc2/assets/447804/8e8ad5fd-ad3b-403a-ab0f-e322b4167121)

```
rclcpp$ grep -rI LargeMessage 
test/rclcpp/test_publisher_with_type_adapter.cpp:struct TypeAdapter<std::string, rclcpp::msg::LargeMessage>
test/rclcpp/test_publisher_with_type_adapter.cpp:  using ros_message_type = rclcpp::msg::LargeMessage;
test/rclcpp/test_publisher_with_type_adapter.cpp:  using StringTypeAdapter = rclcpp::TypeAdapter<std::string, rclcpp::msg::LargeMessage>;
test/rclcpp/test_publisher_with_type_adapter.cpp:  using StringTypeAdapter = rclcpp::TypeAdapter<std::string, rclcpp::msg::LargeMessage>;
test/rclcpp/CMakeLists.txt:  ../msg/LargeMessage.msg
```

We should limit the discovery of messages to be in the msg directory.

**Comment by rkent** [comment]
I see the problem.

[The Developer guide](https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Developer-Guide.html#package-layout) for package layout does not mention the location of messages, services, and actions, but it does give locations for /test and /doc. If I followed that specifically, I would exclude /test and /doc rather than only include /msg, /srv, and /action. Is there an official source that restricts these to specific named folders?

Note the test case full_package specifically includes a test case (for the service) that is outside the "official" location.

**Comment by tfoote** [comment]
The message generation processes will only look in those directories. I've opened a PR for https://github.com/ros2/ros2_documentation/pull/4246 to add it to the developer guide.
